### PR TITLE
Only attempt to stop observation if previously observed

### LINKED ISSUE #142: Crash if connection not established and CoroutineScope cancels
I am first subscribing for notifications (using `observe`) then trying to connect to my peripheral (`connect`).
Actually my device is not available so no connection is established and no services discovered of course.

Then I am exiting from this screen (and thus the couroutine scope is cancelling). At this moment I am getting crash:

```java
java.lang.IllegalStateException: Services have not been discovered for Peripheral(bluetoothDevice=00:80:E1:26:79:3D)
        at com.juul.kable.AndroidPeripheral.getPlatformServices(Peripheral.kt:126)
        at com.juul.kable.AndroidPeripheral.stopObservation$core_debug(Peripheral.kt:289)
        at com.juul.kable.Observers$acquire$4.invokeSuspend(Observers.kt:81)
        at com.juul.kable.Observers$acquire$4.invoke(Unknown Source:13)
        at com.juul.kable.Observers$acquire$4.invoke(Unknown Source:6)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt.invokeSafely$FlowKt__EmittersKt(Emitters.kt:216)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt.access$invokeSafely(Emitters.kt:1)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:121)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt$onCompletion$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:233)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:244)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
        at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:184)
        at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:191)
        at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1474)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1499)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1465)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1499)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1465)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1499)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
        at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:183)
        at androidx.lifecycle.BlockRunner$cancel$1.invokeSuspend(CoroutineLiveData.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421)
```

As I understand it tries to stop observation which actually was not started because no connection established... it is not unclear for me why it requires discovered services and crashes?

### PR DESCRIPTION
**Pull request by twyatt**
Fixes #142.

When `observe` is called, internally it waits until connection is ready before initiating indicate/notify with the peripheral. At which time we increment a counter (of number of subscribers). When performing the reverse operation, we spin down the observation (i.e. inform the OS to disable indicate/notify of characteristic) when the last consumer of an `observe` unsubscribes. If a connection had never been established then upon the last consumer unsubscribing, we'd erroneously attempt to stop the indicate/notify of the characteristic.

By returning `-1` to indicate no previous indicate/notify for that observation has been performed, then we can skip the inverse process (of spinning the observe down).

The crash was due to the fact that we perform characteristic lookups to spin up/down the observations, and if a connection had never been established, then there would be no cached characteristics to search.

### CODE REVIEW

File: core/src/androidMain/kotlin/Observers.kt [hunk 1]
```diff
@@ -135,7 +135,7 @@ private class Observations {
     ): Int = lock.withLock {
         val actions = observations[characteristic]
         when {
-            actions == null -> 0
+            actions == null -> -1 // -1 signifies that no previous observation existed for characteristic.
```
Comment (twyatt) [inline core/src/androidMain/kotlin/Observers.kt:138]:
```suggestion
            actions == null -> -1 // No previous observation existed for characteristic.
```

File: core/src/appleMain/kotlin/Observers.kt [hunk 2]
```diff
@@ -139,7 +139,7 @@ private class Observations : IsolateState<MutableMap<Characteristic, MutableList
     ): Int = access {
         val actions = it[characteristic]
         when {
-            actions == null -> 0
+            actions == null -> -1 // -1 signifies that no previous observation existed for characteristic.
```
Comment (twyatt) [inline core/src/appleMain/kotlin/Observers.kt:142]:
```suggestion
            actions == null -> -1 // No previous observation existed for characteristic.
```

File: core/src/jsMain/kotlin/Observers.kt [hunk 3]
```diff
@@ -98,7 +98,7 @@ private class Observations {
     ): Int {
         val actions = observations[characteristic]
         return when {
-            actions == null -> 0
+            actions == null -> -1 // -1 signifies that no previous observation existed for characteristic.
```
Comment (twyatt) [inline core/src/jsMain/kotlin/Observers.kt:101]:
```suggestion
            actions == null -> -1 // No previous observation existed for characteristic.
```

**Review by cedrickcooke — APPROVED** [review]

**Review by sdonn3 — APPROVED** [review]
