### PR TITLE
Handle bluetooth adapter state changes

### LINKED ISSUE #102: [Android] peripheral.read() hangs after manually disabling bluetooth
We're frequently polling `peripheral.read()` on a background coroutine and noticed that manually disabling bluetooth will not always throw an exception

An exception _will_ be thrown if the read occurs after the OS disconnects from the device:

> 2021-05-18 11:39:35.032 14297-15286/com.v I/FTRepository: start read
2021-05-18 11:39:35.471 14297-15286/com.v I/FTRepository: finish read
2021-05-18 11:39:35.481 14297-15286/com.v I/FTRepository: start read
2021-05-18 11:39:35.650 14297-15286/com.v I/FTRepository: finish read
2021-05-18 11:39:35.654 14297-16277/com.v D/BluetoothGatt: onBluetoothStateChange: up=false
2021-05-18 11:39:35.654 14297-16277/com.v D/BluetoothGatt: Bluetooth is turned off, disconnect all client connections
2021-05-18 11:39:35.654 14297-16277/com.v D/BluetoothGatt: close()
2021-05-18 11:39:35.658 14297-16277/com.v D/BluetoothGatt: unregisterApp() - mClientIf=15
2021-05-18 11:39:35.661 14297-15286/com.v I/FTRepository: start read
2021-05-18 11:39:35.662 14297-15286/com.v E/FTRepository: com.juul.kable.GattRequestRejectedException

And exception will _not_ be thrown if the read occurs before the OS disconnects:

> 2021-05-18 11:11:36.786 11390-12135/com.v I/FTRepository: start read
2021-05-18 11:11:36.956 11390-12135/com.v I/FTRepository: finish read
2021-05-18 11:11:36.966 11390-12135/com.v I/FTRepository: start read
2021-05-18 11:11:37.135 11390-12135/com.v I/FTRepository: finish read
2021-05-18 11:11:37.146 11390-12135/com.v I/FTRepository: start read <-- hangs forever
2021-05-18 11:11:37.251 11390-12401/com.v D/BluetoothGatt: onBluetoothStateChange: up=false
2021-05-18 11:11:37.251 11390-12401/com.v D/BluetoothGatt: Bluetooth is turned off, disconnect all client connections
2021-05-18 11:11:37.251 11390-12401/com.v D/BluetoothGatt: close()
2021-05-18 11:11:37.254 11390-12401/com.v D/BluetoothGatt: unregisterApp() - mClientIf=15
2021-05-18 11:11:37.255 11390-12200/com.v I/BluetoothAdapter: onBluetoothStateChange: up=false

### PR DESCRIPTION
**Pull request by cedrickcooke**
Uses a `BroadcastReceiver` to detect when bluetooth has been turned off at the OS level. As an aside, hopefully this addresses #102.

Also changes the name of the private `dispose` function, because I was getting it confused with `Disposable.dispose`, which has very different semantics.

### CODE REVIEW

File: core/src/androidMain/kotlin/Peripheral.kt [hunk 1]
```diff
@@ -113,8 +118,21 @@ public class AndroidPeripheral internal constructor(
...
 
+    private val receiver = object : BroadcastReceiver() {
+        override fun onReceive(context: Context, intent: Intent) {
+            val state = intent.getIntExtra(BluetoothAdapter.EXTRA_STATE, BluetoothAdapter.ERROR)
+            if (state == BluetoothAdapter.STATE_OFF) {
+                closeConnection()
+                _state.value = State.Disconnected()
+            }
+        }
+    }.also { applicationContext.registerReceiver(it, IntentFilter(BluetoothAdapter.ACTION_STATE_CHANGED)) }
```
Comment (twyatt) [inline core/src/androidMain/kotlin/Peripheral.kt:129]: nit: We could make this slightly more readable in this class.

```suggestion
    private val receiver = onBluetoothOff {
        closeConnection()
        _state.value = State.Disconnected()
    }
```

_In another file:_

```kotlin
internal inline fun onBluetoothOff(crossinline action: () -> Unit): BroadcastReceiver {
    val receiver = object : BroadcastReceiver() {
        override fun onReceive(context: Context, intent: Intent) {
            val state = intent.getIntExtra(BluetoothAdapter.EXTRA_STATE, BluetoothAdapter.ERROR)
            if (state == BluetoothAdapter.STATE_OFF) action.invoke()
        }
    }
    applicationContext.registerReceiver(receiver, IntentFilter(BluetoothAdapter.ACTION_STATE_CHANGED))
    return receiver
}
```

**Review by twyatt — APPROVED** [review]
🚀 💯

**Comment by twyatt** [comment]
Updated PR description to unlink from #102 until we've confirmed the fix.

**Review by sdonn3 — APPROVED** [review]
